//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS_DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentInformationSystemEntities : DbContext
    {
        public StudentInformationSystemEntities()
            : base("name=StudentInformationSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblCity> tblCity { get; set; }
        public DbSet<tblCollege> tblCollege { get; set; }
        public DbSet<tblCollegeDepartment> tblCollegeDepartment { get; set; }
        public DbSet<tblDepartment> tblDepartment { get; set; }
        public DbSet<tblRoles> tblRoles { get; set; }
        public DbSet<tblSemester> tblSemester { get; set; }
        public DbSet<tblState> tblState { get; set; }
        public DbSet<tblStudent> tblStudent { get; set; }
        public DbSet<tblStudentHistory> tblStudentHistory { get; set; }
        public DbSet<tblSubject> tblSubject { get; set; }
        public DbSet<tblSubjectDepartment> tblSubjectDepartment { get; set; }
        public DbSet<tblUniversity> tblUniversity { get; set; }
        public DbSet<tblUserInfo> tblUserInfo { get; set; }
    }
}
