//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoles
    {
        public System.Guid ID { get; set; }
        public int RoleID { get; set; }
        public string RoleName { get; set; }
    }
}
