//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubjectDepartment
    {
        public System.Guid ID { get; set; }
        public Nullable<int> SubjectCode { get; set; }
        public Nullable<int> SemesterID { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
    }
}
