//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentHistory
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> StudentID { get; set; }
        public Nullable<int> CollegeCode { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public Nullable<int> Semester { get; set; }
        public System.DateTime LogDate { get; set; }
    
        public virtual tblStudent tblStudent { get; set; }
    }
}
