//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserInfo
    {
        public System.Guid UserID { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleID { get; set; }
    }
}
